environment:
  matrix:
    - nodejs_version: "8.0"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm -v
  - npm cache verify
  - rm -rf node_modules/
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
  - npm install jest-cli --save-dev
build: off
test_script:
  - node --version
  - npm --version
  - npm test
version: "{build}"
